name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.app.kgcpl.com
          username: u757980258.salvinit
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          # server-dir: /home/u757980258/domains/app.kgcpl.com/public_html/
          server-dir: ./